=== Plenglin/magix-rpg/core/assets/data/schema/weaponTypes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="weaponList">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="meleeWeapon" maxOccurs="unbounded">
                    <xs:complexType>

                        <xs:sequence>
                            <xs:element name="texture" type="xs:string" minOccurs="0" maxOccurs="1" default="item/dagger.png"/>
                        </xs:sequence>

                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="cost" type="xs:decimal"/>
                        <xs:attribute name="damage" type="xs:decimal"/>
                        <xs:attribute name="speed" type="xs:decimal"/>
                        <xs:attribute name="toughness" type="xs:decimal"/>
                        <xs:attribute name="range" type="xs:decimal"/>
                        <xs:attribute name="weight" type="xs:decimal"/>

                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Plenglin/magix-rpg/core/assets/data/weaponTypes.xml
<?xml version="1.0" encoding="UTF-8" ?>


<weaponList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/weaponTypes.xsd">
    <meleeWeapon name="dagger"      cost="200" damage="5"   speed="2.00"    toughness="250" range="0.5" weight="0.50">
        <texture tint="FFFFFF" path="items/dagger.png"/>
    </meleeWeapon>
    <meleeWeapon name="shortsword"  cost="300" damage="10"  speed="1.25"    toughness="350" range="1"   weight="0.75"/>
    <meleeWeapon name="rapier"      cost="300" damage="10"  speed="1.50"    toughness="350" range="2"   weight="1.00"/>
    <meleeWeapon name="broadsword"  cost="500" damage="15"  speed="1.00"    toughness="550" range="1.5" weight="1.50"/>
    <meleeWeapon name="longsword"   cost="500" damage="20"  speed="0.75"    toughness="500" range="2"   weight="1.50"/>
    <meleeWeapon name="battleaxe"   cost="650" damage="30"  speed="0.5"     toughness="750" range="2"   weight="3"/>
</weaponList>
